M48
; DRILL file {KiCad 9.0.6} date 2025-12-01T09:21:38+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-12-01T09:21:38+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X6.024Y-4.8245
X6.024Y-5.2245
T2
X5.5118Y-5.1181
X5.6118Y-5.1181
X5.7118Y-5.1181
M30
